# Site settings
title: The mothur blog
email: pschloss@umich.edu
description: "A discussion of quantitative isues in microbial ecology"
baseurl: ""
url: "http://blog.mothur.org"
twitter_username: patschloss
github_username:  pschloss

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: pretty

github:
  repo:           github.com/mothurblog/mothurblog.github.io
