# Site settings
title: The mothur blog
email: pschloss@umich.edu
description: "A discussion of quantitative isues in microbial ecology"
baseurl: ""
url: "http://blog.mothur.org"
twitter_username: patschloss
github_username:  pschloss

# Build settings
permalink: pretty
markdown: redcarpet
github:
  repo:           github.com/mothurblog/mothurblog.github.io

gems:
  - jekyll-sitemap

